train_test_split_is: True
hyperparameters_optimization_is: False
save_model: lgbm_weights
predict_and_save_test_data: True
blending: False

clearml:
  project_name: "Alfa_hack"
  task_name: "Blending LGBM train full_dataset 07.11.24 v1.0"
  queue: null

dataset_train:
  project_name: "Alfa_hack"
  dataset_name: "train_data_full"
  file_name: "train_dataset.parquet"
  target_columns: target

dataset_test:
  project_name: "Alfa_hack"
  dataset_name: "test_dataset"
  file_name: "test_dataset.parquet"

model:
  n_estimators: 127
  learning_rate: 0.012835847658688107
  max_depth: 18
  subsample: 0.7925881420008511
  colsample_bytree: 0.8773532749104792
  reg_alpha: 1.700386005699518
  reg_lambda: 1.5332314072612385
  random_state: 8


hyperparameters:
  n_trials: 100