train_test_split_is: True
hyperparameters_optimization_is: False
save_model: null
predict_and_save_test_data: True
blending: True

clearml:
  project_name: "Alfa_hack"
  task_name: "Blending final LogReg train and predict full_dataset 07.11.24 v1.1"
  queue: null

dataset_train:
  project_name: "Alfa_hack"
  dataset_name: "train_data_full"
  file_name: "train_dataset.parquet"
  target_columns: target

dataset_test:
  project_name: "Alfa_hack"
  dataset_name: "test_dataset"
  file_name: "test_dataset.parquet"

model:
  C: 0.15674
  solver: "lbfgs"
  penalty: "l2"
  random_state: 1234
  class_weight: "balanced"


hyperparameters:
  n_trials: 100