train_test_split_is: True
hyperparameters_optimization_is: True
save_model: null
predict_and_save_test_data: False
blending: False

clearml:
  project_name: "Alfa_hack"
  task_name: "LGBM hyperparameters sub_train_dataset 07.11.24 v1.0"
  queue: null

dataset_train:
  project_name: "Alfa_hack"
  dataset_name: "train_data_sub"
  file_name: "sub_train_dataset.parquet"
  target_columns: target

dataset_test:
  project_name: "Alfa_hack"
  dataset_name: "test_dataset"
  file_name: "test_dataset.parquet"

model:
  C: 0.546
  kernel: "rbf"
  gamma: "scale"
  random_state: 64
  probability: True
  class_weight: "balanced"
  max_iter: 10000


hyperparameters:
  n_trials: 100