train_test_split_is: False
hyperparameters_optimization_is: False
save_model: FTT_models
predict_and_save_test_data: True

clearml:
  project_name: "Alfa_hack"
  task_name: "FTT train train full dataset 12.11.24 v1.0"
  queue: null

dataset_train:
  project_name: "Alfa_hack"
  dataset_name: "train_data_full"
  file_name: "train_dataset.parquet"
  target_columns: target

dataset_test:
  project_name: "Alfa_hack"
  dataset_name: "test_dataset"
  file_name: "test_dataset.parquet"

model:
  name: FTT

hyperparameters:
  n_trials: 100