train_test_split_is: True
hyperparameters_optimization_is: True
save_model: null
predict_and_save_test_data: False

clearml:
  project_name: "Alfa_hack"
  task_name: "XGBoost hyperparameters sub_train_dataset 05.11.24"
  queue: null

dataset_train:
  project_name: "Alfa_hack"
  dataset_name: "train_data_sub"
  file_name: "sub_train_dataset.parquet"
  target_columns: target

dataset_test:
  project_name: "Alfa_hack"
  dataset_name: "test_dataset"
  file_name: "test_dataset.parquet"

model:
  C: 0.01
  random_state: 98
  max_iter: 150

hyperparameters:
  n_trials: 250