train_test_split_is: True
hyperparameters_optimization_is: False
save_model: logreg_weights
predict_and_save_test_data: True
blending: True

clearml:
  project_name: "Alfa_hack"
  task_name: "Blending LogReg final train full_dataset 08.11.24 v1.3"
  queue: "default"

dataset_train:
  project_name: "Alfa_hack"
  dataset_name: "train_data_full"
  file_name: "train_dataset.parquet"
  target_columns: target

dataset_test:
  project_name: "Alfa_hack"
  dataset_name: "test_dataset"
  file_name: "test_dataset.parquet"

model:
  C: 0.56
  solver: saga
  penalty: elasticnet
  l1_ratio: 0.4
  max_iter: 15000
  random_state: 78
  # class_weight: balanced


hyperparameters:
  n_trials: 100